<a href="https://colab.research.google.com/github/Rob7799/Homework_numpy/blob/main/NumPy_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [4]:
array2=np.array([[1,2,3],
                [4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
array3=np.array([[[20,40,50],
                  [3,4,99],
                 [100,22,11]],
                [[23,22,12],
                 [99,33,233],
                 [100,8,2]]])
array3

array([[[ 20,  40,  50],
        [  3,   4,  99],
        [100,  22,  11]],

       [[ 23,  22,  12],
        [ 99,  33, 233],
        [100,   8,   2]]])

In [6]:
array1.shape

(3,)

In [7]:
array1.ndim


1

In [8]:
array1.dtype

dtype('int64')

In [9]:
array1.size

3

In [10]:
type(array1)


numpy.ndarray

In [11]:
array2.shape, array2.ndim, array2.dtype, array2.size, type(array2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [12]:
array3.shape, array3.ndim, array3.dtype, array3.size, type(array3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [13]:
import pandas as pd

In [14]:
df=pd.DataFrame(array2)
df

0  1  2
0  1  2  3
1  4  5  6

In [15]:
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
np.arange(0,100,3)


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [18]:
np.random.randint(10,size=(7,2))

array([[3, 9],
       [4, 5],
       [0, 6],
       [4, 9],
       [5, 9],
       [1, 2],
       [5, 4]])

In [19]:
np.random.random((3,5))

array([[0.44647086, 0.66186985, 0.61068102, 0.34247043, 0.12983624],
       [0.75429227, 0.57714725, 0.49071412, 0.92965974, 0.36875908],
       [0.99087824, 0.33645091, 0.07637915, 0.86423238, 0.03379453]])

In [20]:
truck=np.random.seed(42)
truck

In [21]:
cat=np.random.randint(10, size=(3,7))
cat

array([[6, 3, 7, 4, 6, 9, 2],
       [6, 7, 4, 3, 7, 7, 2],
       [5, 4, 1, 7, 5, 1, 4]])

In [22]:
cat[0] #14

array([6, 3, 7, 4, 6, 9, 2])

In [27]:
print(cat[0:2])


[[6 3 7 4 6 9 2]
 [6 7 4 3 7 7 2]]


In [29]:
cat[0:2,0:2]

array([[6, 3],
       [6, 7]])

In [32]:
dog=np.random.randint(10, size=(3,5)) #17
dog

array([[3, 8, 1, 9, 8],
       [9, 4, 1, 3, 6],
       [7, 2, 0, 3, 1]])

In [36]:
tiger=np.ones((3,5))
tiger

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
zoo=tiger+dog
zoo

array([[ 4.,  9.,  2., 10.,  9.],
       [10.,  5.,  2.,  4.,  7.],
       [ 8.,  3.,  1.,  4.,  2.]])

In [42]:
np.ones((3,5)).shape
ant=np.ones((3,5))
ant

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
farm=zoo+ant

In [47]:
monkey=np.ones((3,5))
monkey

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
bird=farm-monkey

In [52]:
time=monkey*bird #23
time

array([[ 4.,  9.,  2., 10.,  9.],
       [10.,  5.,  2.,  4.,  7.],
       [ 8.,  3.,  1.,  4.,  2.]])

In [53]:
time**2

array([[ 16.,  81.,   4., 100.,  81.],
       [100.,  25.,   4.,  16.,  49.],
       [ 64.,   9.,   1.,  16.,   4.]])

In [54]:
np.square(time)

array([[ 16.,  81.,   4., 100.,  81.],
       [100.,  25.,   4.,  16.,  49.],
       [ 64.,   9.,   1.,  16.,   4.]])

In [55]:
np.mean(time)

5.333333333333333

In [56]:
np.max(time)

10.0

In [57]:
np.min(time)

1.0

In [58]:
np.std(time)

3.0912061651652345

In [59]:
np.var(time)

9.555555555555555

In [64]:
dolphin=time.reshape(3,5,1)
dolphin

array([[[ 4.],
        [ 9.],
        [ 2.],
        [10.],
        [ 9.]],

       [[10.],
        [ 5.],
        [ 2.],
        [ 4.],
        [ 7.]],

       [[ 8.],
        [ 3.],
        [ 1.],
        [ 4.],
        [ 2.]]])

In [66]:
hat=dolphin.transpose()
hat

array([[[ 4., 10.,  8.],
        [ 9.,  5.,  3.],
        [ 2.,  2.,  1.],
        [10.,  4.,  4.],
        [ 9.,  7.,  2.]]])

In [83]:
clock=np.random.randint(10,size=(3,3))
table=np.random.randint(10,size=(3,2))

In [69]:
table

array([[1, 4],
       [7, 9],
       [8, 8]])

In [70]:
clock #33

array([[9, 1, 9],
       [3, 7, 6],
       [8, 7, 4]])

In [78]:
np.dot(table,clock) #34 Have to change the dimensions to be the same for .dot to work



array([[ 70,  63,   4],
       [ 28,  44,  20],
       [111, 177,  72]])

In [89]:
red=table.transpose()
yellow=clock.transpose()

In [90]:
np.dot(red,yellow)

array([[ 61,  84,  41],
       [ 98, 117,  50]])

In [93]:
wood=np.random.randint(10,size=(4,2))
tree=np.random.randint(10,size=(4,2))
wood
tree

wood>tree

array([[False,  True],
       [False, False],
       [False, False],
       [False,  True]])

In [94]:
wood

array([[0, 7],
       [0, 0],
       [1, 1],
       [5, 6]])

In [95]:
tree

array([[4, 0],
       [0, 2],
       [1, 4],
       [9, 5]])

In [96]:
tree

array([[4, 0],
       [0, 2],
       [1, 4],
       [9, 5]])

In [97]:
wood

array([[0, 7],
       [0, 0],
       [1, 1],
       [5, 6]])

In [98]:
tree>=wood

array([[ True, False],
       [ True,  True],
       [ True,  True],
       [ True, False]])

In [106]:
tree.sort()
print(tree)


[[0 4]
 [0 2]
 [1 4]
 [5 9]]


In [110]:
tree>7

array([[False, False],
       [False, False],
       [False, False],
       [False,  True]])

In [111]:
tree==wood

array([[ True, False],
       [ True, False],
       [ True, False],
       [ True, False]])

In [112]:
tree

array([[0, 4],
       [0, 2],
       [1, 4],
       [5, 9]])

In [113]:
wood

array([[0, 7],
       [0, 0],
       [1, 1],
       [5, 6]])

In [116]:
np.argsort(tree)
np.argsort(wood)

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1]])

In [117]:
np.argsort(wood)

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1]])

In [119]:
np.argmax(wood) #Find the Index with Max value #45

1

In [120]:
np.argmin(wood)

0

In [121]:
tree

array([[0, 4],
       [0, 2],
       [1, 4],
       [5, 9]])

In [122]:
np.max(tree)

9

In [128]:
smile=np.argsort(tree)
smile

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1]])

In [129]:
np.max(smile)

1

In [131]:
np.argmax(smile,axis=1)   # When Axis=0 it is rows. When Axis=1 it's columns

array([1, 1, 1, 1])

In [133]:
np.argmin(smile,axis=0) 

array([0, 0])

array([], shape=(0, 10), dtype=int64)

array([], shape=(0, 10), dtype=int64)

In [141]:
np.random.randint(10, size=(2,10))

array([[5, 5, 0, 8, 5, 2, 3, 3, 2, 9],
       [2, 2, 3, 6, 3, 8, 0, 7, 6, 1]])

In [146]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])